<?php

return [
    /**
     * Current environment (dummy, pre-prod, prod)
     */
    'env' => env('MOL_ENV', 'dummy'),

    /**
     * Return path
     */
    'return_to' => '/auth/openid/login',

    /**
     * Environment configuration
     */
    'envs' => [
        'dummy' => [
            'endpoint' => '/auth/openid/authenticate',
        ],

        'prod' => [
            'endpoint'  => 'https://www.mol.gov.sa/openid/provider.ashx',
            'return_to' => '/auth/openid/authenticate',
        ],
        'pre-prod' => [
            'endpoint'  => 'http://192.168.209.52:260/openid/provider.ashx',
            'return_to' => '/auth/openid/authenticate',
        ],
    ],

    /**
     * Data
     */
    'data' => [
        'establishments' => [
            [
                'FK_establishment_id'       => 1,
                'labor_office_id'           => 1,
                'sequence_number'           => 1,
                'name'                      => 'منشأة تجريبية #1',
                'FK_economic_activity_id'   => 10,
                'economic_activity'         => 'السياحة',
                'main_economic_activity'    => 30,
                'sub_economic_activity'     => 3697,
                'nitaqat_economic_activity' => 10,
                'status_id'                 => 1,
                'status'                    => 1,
                'cr_number'                 => 100,
                'cr_end_date'               => '01-01-2016',
                'statement_number'          => '13215-25',
                'statement_end_date'        => '01-01-2016',
                'wasel_status'              => 1,
                'wasel_end_date'            => '01-01-2016',
                'wasel_expiry_date'         => '10-12-2016',
                'nitaqat_color_id'          => 300,
                'nitaqat_color'             => 'أخضر منخفض',
                'size_id'                   => 2,
                'unused_visas'              => 1,
                'owner'                     => '1068212040'
            ],
            [
                'FK_establishment_id'       => 2,
                'labor_office_id'           => 1,
                'sequence_number'           => 2,
                'name'                      => 'منشأة تجريبية #2',
                'FK_economic_activity_id'   => 10,
                'economic_activity'         => 'الصيدليات',
                'main_economic_activity'    => 30,
                'sub_economic_activity'     => 3697,
                'nitaqat_economic_activity' => 10,
                'status_id'                 => 1,
                'status'                    => 1,
                'cr_number'                 => 200,
                'cr_end_date'               => '10-10-2015',
                'statement_number'          => '13215-25',
                'statement_end_date'        => '10-10-2015',
                'wasel_status'              => 1,
                'wasel_end_date'            => '01-01-2016',
                'wasel_expiry_date'         => '10-12-2015',
                'nitaqat_color_id'          => 1,
                'nitaqat_color'             => 'احمر منخفض',
                'size_id'                   => 2,
                'unused_visas'              => 1,
                'owner'                     => '1068212040'
            ],
            [
                'FK_establishment_id'       => 3,
                'labor_office_id'           => 1,
                'sequence_number'           => 3,
                'name'                      => 'منشأة تجريبية #3',
                'FK_economic_activity_id'   => 14,
                'economic_activity'         => 'الصيدليات',
                'main_economic_activity'    => 30,
                'sub_economic_activity'     => 3697,
                'nitaqat_economic_activity' => 14,
                'status_id'                 => 1,
                'status'                    => 1,
                'cr_number'                 => 200,
                'cr_end_date'               => '01-01-2016',
                'statement_number'          => '13215-25',
                'statement_end_date'        => '01-01-2016',
                'wasel_status'              => 1,
                'wasel_end_date'            => '01-01-2016',
                'wasel_expiry_date'         => '10-12-2015',
                'nitaqat_color_id'          => 300,
                'nitaqat_color'             => 'أخضر منخفض',
                'size_id'                   => 2,
                'unused_visas'              => 1,
                'owner'                     => '1068212040'
            ],
            [
                'FK_establishment_id'       => 4,
                'labor_office_id'           => 1,
                'sequence_number'           => 4,
                'name'                      => 'منشأة تجريبية #4',
                'FK_economic_activity_id'   => 37,
                'economic_activity'         => 'المدارس',
                'main_economic_activity'    => 30,
                'sub_economic_activity'     => 3697,
                'nitaqat_economic_activity' => 37,
                'status_id'                 => 1,
                'status'                    => 1,
                'cr_number'                 => 203252352350,
                'cr_end_date'               => '01-01-2016',
                'statement_number'          => '13215-25',
                'statement_end_date'        => '01-01-2016',
                'wasel_status'              => 1,
                'wasel_end_date'            => '01-01-2016',
                'wasel_expiry_date'         => '10-12-2015',
                'nitaqat_color_id'          => 300,
                'nitaqat_color'             => 'أخضر منخفض',
                'size_id'                   => 3,
                'low_green_quota'           => 10,
                'owner'                     => '1068212040'
            ],
        ],

        'laborers' => [
            [
                'id_number'             => '2222222222',
                'id'                    => 1,
                'name'                  => 'KOSTAS VIOLARIS',
                'job'                   => 'فني في الهندسة الميكانيكة -عام',
                'job_id'                => 3215052,
                'nationality'           => 'قبرصي',
                'nationality_id'        => 370,
                'FK_establishment_id'   => 1,
                'labor_office_id'       => 1,
                'sequence_number'       => 1,
                'religion'              => 2,
                'gender'                => 1,
                'birth_year'            => 1379,
                'entry_date'            => '2006-01-08 00:00:00.000',
                'educational_status'    => 'لايوجد',
                'educational_status_id' => 0,
                'qualification'         => 'رموز المؤهل والتخصص-القوى العاملة والتوظيف',
                'qualification_id'      => 0,
            ],
            [
                'id_number'             => '2042243648',
                'id'                    => 2,
                'name'                  => 'محمد عبدالله الثور باوزيز',
                'job'                   => 'عامل',
                'job_id'                => 6132115,
                'nationality'           => 'يمني',
                'nationality_id'        => 326,
                'FK_establishment_id'   => 1,
                'labor_office_id'       => 1,
                'sequence_number'       => 1,
                'religion'              => 2,
                'gender'                => 1,
                'birth_year'            => 1382,
                'entry_date'            => '1987-08-25 00:00:00.000',
                'educational_status'    => 'لايوجد',
                'educational_status_id' => 0,
                'qualification'         => 'رموز المؤهل والتخصص-القوى العاملة والتوظيف',
                'qualification_id'      => 0,
            ],
            [
                'id_number'             => '2068242607',
                'id'                    => 3,
                'name'                  => 'HANEEFA KUNJU - HAMSA',
                'job'                   => 'عامل شحن و تفريغ',
                'job_id'                => 6321015,
                'nationality'           => 'هندي',
                'nationality_id'        => 377,
                'FK_establishment_id'   => 1,
                'labor_office_id'       => 1,
                'sequence_number'       => 1,
                'religion'              => 1,
                'gender'                => 1,
                'birth_year'            => 1387,
                'entry_date'            => '1991-12-09 00:00:00.000',
                'educational_status'    => 'يقرأ و يكتب',
                'educational_status_id' => 2,
                'qualification'         => 'لايوجد',
                'qualification_id'      => 99,
            ],
            [
                'id'                    => 4,
                'id_number'             => '2122496546',
                'name'                  => 'سيف اليزل محمد ميرغني ادريس',
                'job'                   => 'مستشار',
                'job_id'                => 2432991,
                'nationality'           => 'سوداني',
                'nationality_id'        => 316,
                'FK_establishment_id'   => 2,
                'labor_office_id'       => 1,
                'sequence_number'       => 2,
                'religion'              => 1,
                'gender'                => 1,
                'birth_year'            => 1389,
                'entry_date'            => '1996-09-15 00:00:00.000',
                'educational_status'    => 'دكتوراه',
                'educational_status_id' => 10,
                'qualification'         => 'العلوم الإدارية',
                'qualification_id'      => 3,
            ],
            [
                'id_number'             => '2239108604',
                'id'                    => 5,
                'name'                  => 'شريف محمود محمد قاسم',
                'job'                   => 'مبرمج حاسب آلي',
                'job_id'                => 2133031,
                'nationality'           => 'مصرى',
                'nationality_id'        => 323,
                'FK_establishment_id'   => 3,
                'labor_office_id'       => 1,
                'sequence_number'       => 3,
                'religion'              => 1,
                'gender'                => 1,
                'birth_year'            => 1395,
                'entry_date'            => '2007-02-20 00:00:00.000',
                'educational_status'    => 'لايوجد',
                'educational_status_id' => 0,
                'qualification'         => 'رموز المؤهل والتخصص-القوى العاملة والتوظيف',
                'qualification_id'      => 0,
            ],
        ],

        'users' => [
            1 => 1010101010,
            2 => 1068212040,
        ],

        'jobs' => [
            ['id' => 6132035, 'name' => 'عامل تنظيف مستشفيات'],
            ['id' => 6132055, 'name' => 'عامل تنظيف سجاد'],
            ['id' => 6132075, 'name' => 'عامل منزلي'],
            ['id' => 6132085, 'name' => 'مساح احذية'],
            ['id' => 6132105, 'name' => 'مشرف خدمات عامة في سفينة'],
            ['id' => 9112145, 'name' => 'عامل تركيب مواسير عام'],
            ['id' => 9112165, 'name' => 'عامل تركيب مواسير سفنية'],
            ['id' => 9112175, 'name' => 'عامل تركيب'],
            ['id' => 9112205, 'name' => 'مشغل فرن الدست'],
            ['id' => 9112215, 'name' => 'عامل تشكيل مكبس المسبوك (ميكانيكيا)'],
            ['id' => 9113043, 'name' => 'مشغل مخرطة اتوماتيكية'],
            ['id' => 9113074, 'name' => 'مجلخ ادوات قطع'],
            ['id' => 9113105, 'name' => 'مساعد براد'],
            ['id' => 9113135, 'name' => 'مشغل الة تشغيل مبرمجة'],
            ['id' => 9113163, 'name' => 'مراقب على الانتاج في اعمال الخراطة'],
            ['id' => 9114034, 'name' => 'حداد اثاث معدني'],
            ['id' => 9114055, 'name' => 'مساعد حداد اثاث معدني'],
            ['id' => 9114075, 'name' => 'مشغل ثناية صفيح اليه'],
            ['id' => 9114215, 'name' => 'عامل صنع نماذج ارانيك معدنية السبك'],
            ['id' => 9114235, 'name' => 'عامل تصليح بنادق صيد'],
            ['id' => 9114255, 'name' => 'عامل تشكيل المعدن يدويا'],
            ['id' => 9116145, 'name' => 'عامل برشمة -ضغط هوائي'],
            ['id' => 9116155, 'name' => 'لحام المركبات المعدنية'],
            ['id' => 9116185, 'name' => 'عامل قطع باللهب يدويا'],
            ['id' => 9116195, 'name' => 'عامل قطع باللهب اليا'],
            ['id' => 9117015, 'name' => 'عامل تكسية'],
            ['id' => 9117025, 'name' => 'مشغل الة تكسية المعادن بالخارصين (مشغل الة جلفنة)'],
            ['id' => 9117045, 'name' => 'عامل تكسية معادن بالغمر'],
            ['id' => 9117065, 'name' => 'عامل تخمير (لحفر المعادن)'],
            ['id' => 9117075, 'name' => 'عامل مراجعة معادن'],
            ['id' => 9117095, 'name' => 'عامل طلاء بالغمس الساخن'],
            ['id' => 9117105, 'name' => 'عامل طلاء السلك بالماكينة'],
            ['id' => 9117125, 'name' => 'رباب اواني نحاسية'],
            ['id' => 9117135, 'name' => 'عامل طلاء المعادن بالازرق'],
            ['id' => 9117145, 'name' => 'عامل تنظيف المعادن المسبوكة وتنعيمها يدويا'],
            ['id' => 9117165, 'name' => 'عامل تنظيف المعادن بالرش بالمعادن'],
            ['id' => 9118024, 'name' => 'نحاس اوني منزلية'],
            ['id' => 9119013, 'name' => 'صانع حلي ومجوهرات عام'],
            ['id' => 9119043, 'name' => 'جواهرجي'],
            ['id' => 1217771, 'name' => 'مدير المعلومات التجارية والبحوث'],
            ['id' => 2311691, 'name' => 'استشاري طب المناطق الحارة'],
            ['id' => 2311701, 'name' => 'استشاري علم التشريح'],
            ['id' => 2312121, 'name' => 'استشاري جراحة قولون ومستقيم'],
            ['id' => 2312151, 'name' => 'استشاري جراحة اوعية دموية'],
            ['id' => 2312161, 'name' => 'استشاري جراحة دماغ واعصاب'],
            ['id' => 6411095, 'name' => 'خياطة منزلية'],
            ['id' => 6411192, 'name' => 'ممرضة منزلية'],
            ['id' => 6411145, 'name' => 'مزارع منزلي'],
            ['id' => 6411115, 'name' => 'طباخ منزلي'],
            ['id' => 2315361, 'name' => 'أخصائي أجهزة طبية'],
            ['id' => 1111081, 'name' => 'عضو مجلس إدارة'],
            ['id' => 3422012, 'name' => 'معلم'],
        ],

        'nationalities' => [],
    ],
];
